import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
import { Sidebar } from "@/components/Sidebar";
import { UserProvider } from "@/context/userContext";

export const metadata: Metadata = {
  title: "Hackaton - Frontend",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen background font-sans antialiased",
          geistSans.className
        )}
      >
        <UserProvider>
          <Sidebar />
          {children}
          <Toaster />
        </UserProvider>
      </body>
    </html>
  );
}
